name: "Build Ren'Py Project"
author: 'Project Alice'
description: "Build your VN project using a specified Ren'Py SDK version"
inputs:
  sdk-version:
    description: "The version of the Ren'Py SDK to use"
    required: true
    default: '7.3.2'
  project-dir:
    description: "The path to the directory where the project exists"
    required: true
    default: '.'
outputs:
  dir:
    description: "The directory where the distributed files exist"
  version:
    description: "The built version of the project"
runs:
  using: 'docker'
  image: 'moustacheful/renpy:7.4.8'
  args:
    - ${{ inputs.sdk-version }}
    - ${{ inputs.project-dir }}
branding:
  color: 'gray-dark'
  icon: 'archive'
